package de.scmb.scotty.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KeyValueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeyValueAllPropertiesEquals(KeyValue expected, KeyValue actual) {
        assertKeyValueAutoGeneratedPropertiesEquals(expected, actual);
        assertKeyValueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeyValueAllUpdatablePropertiesEquals(KeyValue expected, KeyValue actual) {
        assertKeyValueUpdatableFieldsEquals(expected, actual);
        assertKeyValueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeyValueAutoGeneratedPropertiesEquals(KeyValue expected, KeyValue actual) {
        assertThat(expected)
            .as("Verify KeyValue auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeyValueUpdatableFieldsEquals(KeyValue expected, KeyValue actual) {
        assertThat(expected)
            .as("Verify KeyValue relevant properties")
            .satisfies(e -> assertThat(e.getKvKey()).as("check kvKey").isEqualTo(actual.getKvKey()))
            .satisfies(e -> assertThat(e.getKvValue()).as("check kvValue").isEqualTo(actual.getKvValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKeyValueUpdatableRelationshipsEquals(KeyValue expected, KeyValue actual) {
        // empty method
    }
}
