import dayjs from 'dayjs/esm';

import { IPayment, NewPayment } from './payment.model';

export const sampleWithRequiredData: IPayment = {
  id: 11584,
  mandateId: 'until character before',
  paymentId: 'portly furiously greedy',
  gateway: 'OPENPAYD',
  iban: 'SI95936750730840914',
  bic: 'ZOHNNAQI',
  amount: 25081,
  currencyCode: 'CRC',
  softDescriptor: 'frenetically bashfully down',
  firstName: 'Ardella',
  lastName: 'Herman',
  streetName: '10th Street',
  houseNumber: 'convection flat ',
  postalCode: 'sweetly exotic s',
  city: 'Roweland',
  countryCode: 'HN',
  remoteIp: 'superb tenement',
  emailAddress: 'husky',
  timestamp: dayjs('2024-03-01T12:58'),
  state: 'how wedge readily',
  message: 'rough rapidly meanwhile',
};

export const sampleWithPartialData: IPayment = {
  id: 13062,
  mandateId: 'enlist tame',
  paymentId: 'yowza boo',
  gateway: 'UNKNOWN',
  iban: 'CH658794638U5E2368S69',
  bic: 'KCWYPEVC',
  amount: 4471,
  currencyCode: 'CLP',
  softDescriptor: 'accomplished insignificant wasabi',
  firstName: 'Lora',
  lastName: 'Schimmel',
  streetName: 'Kent Road',
  houseNumber: 'yellow exaggerat',
  postalCode: 'inborn',
  city: 'East Earnestine',
  countryCode: 'HN',
  remoteIp: 'hm zen sate',
  emailAddress: 'barring',
  timestamp: dayjs('2024-02-29T18:34'),
  state: 'acquire besides',
  message: 'vanadyl',
  gatewayId: 'thyme expense',
  mandateDate: dayjs('2024-02-29T21:38'),
  executionDate: dayjs('2024-02-29T21:27'),
  paymentInformationId: 'meanwhile',
};

export const sampleWithFullData: IPayment = {
  id: 13024,
  mandateId: 'punctuation',
  paymentId: 'massage low',
  gateway: 'OPENPAYD',
  iban: 'AL955010804939L8X818226F35FC',
  bic: 'IJYGTLTPXXX',
  amount: 14600,
  currencyCode: 'SYP',
  softDescriptor: 'boo decouple',
  firstName: 'Ollie',
  lastName: 'McKenzie',
  streetName: 'Rowe Lights',
  houseNumber: 'than march once',
  postalCode: 'acidly councilma',
  city: 'Powlowskimouth',
  countryCode: 'KZ',
  remoteIp: 'over whereas till',
  emailAddress: 'considering for hammock',
  timestamp: dayjs('2024-02-29T23:51'),
  state: 'impish except',
  message: 'syringe',
  gatewayId: 'queasy',
  mode: 'sushi unbearably harangue',
  fileName: 'strong excellent pitiful',
  creditorName: 'eventually pale',
  creditorIban: 'ack feminizeXXXX',
  creditorBic: 'provided',
  creditorId: 'status urgently',
  mandateDate: dayjs('2024-03-01T07:27'),
  executionDate: dayjs('2024-02-29T13:33'),
  paymentInformationId: 'stylish',
};

export const sampleWithNewData: NewPayment = {
  mandateId: 'for rosin save',
  paymentId: 'bourgeoisie self-assured pale',
  gateway: 'UNKNOWN',
  iban: 'BE25462060763365',
  bic: 'STQPGUTX',
  amount: 26405,
  currencyCode: 'CLP',
  softDescriptor: 'since',
  firstName: 'Karolann',
  lastName: 'Harris',
  streetName: 'N Chestnut Street',
  houseNumber: 'whoa loose',
  postalCode: 'scram mostly sup',
  city: 'Fort Milfordport',
  countryCode: 'TT',
  remoteIp: 'likewise',
  emailAddress: 'bashfully above pish',
  timestamp: dayjs('2024-03-01T13:04'),
  state: 'if mmm',
  message: 'but big',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
