import dayjs from 'dayjs/esm';

import { IPayment, NewPayment } from './payment.model';

export const sampleWithRequiredData: IPayment = {
  id: 22811,
  mandateId: 'twist',
  paymentId: 'but astride',
  gateway: 'NOVALNET',
  iban: 'PK46VQDH5586874004367394',
  bic: 'HQSNBYZPEAU',
  amount: 25749,
  currencyCode: 'MVR',
  softDescriptor: 'without sniveling',
  firstName: 'Cleta',
  lastName: 'Kohler',
  streetName: 'Cole Run',
  houseNumber: 'charm amendment ',
  postalCode: 'convection flat ',
  city: 'Willstad',
  countryCode: 'MK',
  remoteIp: 'while annex',
  emailAddress: 'obnoxiously superb',
  timestamp: dayjs('2024-02-29T21:20'),
  state: 'successfully without',
  message: 'how wedge readily',
};

export const sampleWithPartialData: IPayment = {
  id: 26807,
  mandateId: 'easy',
  paymentId: 'between',
  gateway: 'OPENPAYD',
  iban: 'IL360576000040098007589',
  bic: 'VNIWGW3P',
  amount: 21800,
  currencyCode: 'BSD',
  softDescriptor: 'tuber',
  firstName: 'Thaddeus',
  lastName: 'Terry',
  streetName: 'Somerset Road',
  houseNumber: 'tarragon frightf',
  postalCode: 'ick',
  city: 'Gutkowskifurt',
  countryCode: 'GU',
  remoteIp: 'suitcase vacation ha',
  emailAddress: 'hyphenation svelte substantial',
  timestamp: dayjs('2024-03-01T11:34'),
  state: 'exaggerate ragged warped',
  message: 'during',
  fileName: 'seal',
};

export const sampleWithFullData: IPayment = {
  id: 133,
  mandateId: 'amidst psst physically',
  paymentId: 'intellect frequent',
  gateway: 'CCBILL',
  iban: 'PK36GSPX0042004179050005',
  bic: 'KESOAOGGXXX',
  amount: 11366,
  currencyCode: 'JMD',
  softDescriptor: 'low yuck',
  firstName: 'Jazmyne',
  lastName: 'Hackett',
  streetName: 'E Cedar Street',
  houseNumber: 'webbed until con',
  postalCode: 'broadly',
  city: 'Ramonaburgh',
  countryCode: 'TM',
  remoteIp: 'whereas',
  emailAddress: 'gently orchestrate poorly',
  timestamp: dayjs('2024-03-01T01:19'),
  state: 'however youthfully jot',
  message: 'unsightly',
  gatewayId: 'brr well-to-do',
  mode: 'march catalyze',
  fileName: 'mysteriously how gosh',
};

export const sampleWithNewData: NewPayment = {
  mandateId: 'coal woot gracefully',
  paymentId: 'deed queasy',
  gateway: 'UNKNOWN',
  iban: 'AZ88WFSV07600106336009666352',
  bic: 'ZNORYELMXXX',
  amount: 4401,
  currencyCode: 'KMF',
  softDescriptor: 'retrospectivity knavishly respray',
  firstName: 'Sherwood',
  lastName: 'Kuvalis',
  streetName: 'Danika Curve',
  houseNumber: 'ew',
  postalCode: 'revoke',
  city: 'Avondale',
  countryCode: 'BR',
  remoteIp: 'unabashedly',
  emailAddress: 'questioningly roughly failing',
  timestamp: dayjs('2024-02-29T21:15'),
  state: 'as recompense hunt',
  message: 'though',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
