import dayjs from 'dayjs/esm';

import { IReconciliation, NewReconciliation } from './reconciliation.model';

export const sampleWithRequiredData: IReconciliation = {
  id: 28122,
  mandateId: 'yuck',
  paymentId: 'how mid',
  gateway: 'CCBILL',
  iban: 'IL430405550700243055005',
  bic: 'RQALSYTZIFR',
  amount: 19136,
  currencyCode: 'INR',
  softDescriptor: 'respectful beyond',
  firstName: 'Viola',
  lastName: 'Beier',
  streetName: 'Frederik Trafficway',
  houseNumber: 'glum',
  postalCode: 'carload journali',
  city: 'Patrickhaven',
  countryCode: 'AS',
  remoteIp: 'than fussy',
  emailAddress: 'crossly comply',
  timestamp: dayjs('2024-02-29T21:28'),
  state: 'grid incidentally',
  reasonCode: 'conciliate arch',
  message: 'through',
};

export const sampleWithPartialData: IReconciliation = {
  id: 19269,
  mandateId: 'rarely',
  paymentId: 'snappy victoriously like',
  gateway: 'CCBILL',
  iban: 'KW11LTMEB006702563AM3A82156696',
  bic: 'IBCINCC3Y14',
  amount: 13629,
  currencyCode: 'BBD',
  softDescriptor: 'as',
  firstName: 'Alysson',
  lastName: 'Zboncak',
  streetName: 'Melany Parkway',
  houseNumber: 'apt',
  postalCode: 'driving villa',
  city: 'West Meggiestad',
  countryCode: 'AR',
  remoteIp: 'fooey',
  emailAddress: 'climate pleasing hm',
  timestamp: dayjs('2024-03-01T00:58'),
  state: 'suddenly apud',
  reasonCode: 'than until',
  message: 'dry lest pish',
  gatewayId: 'out triumphantly misreport',
};

export const sampleWithFullData: IReconciliation = {
  id: 22748,
  mandateId: 'for',
  paymentId: 'floodlight',
  gateway: 'CCBILL',
  iban: 'LB43646917007957C5515019X483',
  bic: 'VPPBMY2E',
  amount: 24156,
  currencyCode: 'BGN',
  softDescriptor: 'consequently pressurise after',
  firstName: 'Liza',
  lastName: "O'Kon",
  streetName: 'Walker Passage',
  houseNumber: 'towards',
  postalCode: 'though promulgat',
  city: 'Arlieberg',
  countryCode: 'LC',
  remoteIp: 'backlight minus',
  emailAddress: 'atop',
  timestamp: dayjs('2024-03-01T05:33'),
  state: 'pace',
  reasonCode: 'ew',
  message: 'even hmph swing',
  gatewayId: 'grounded prickle until',
  mode: 'vice psst crafty',
  fileName: 'whoa lonely powerfully',
};

export const sampleWithNewData: NewReconciliation = {
  mandateId: 'yippee chive anti',
  paymentId: 'yuck',
  gateway: 'EMERCHANTPAY',
  iban: 'BE72080886030070',
  bic: 'EELPCDW5',
  amount: 5604,
  currencyCode: 'YER',
  softDescriptor: 'crow barring',
  firstName: 'Tad',
  lastName: 'Hessel',
  streetName: 'E High Street',
  houseNumber: 'strand exactly p',
  postalCode: 'persimmon gag',
  city: 'Lake Darrinboro',
  countryCode: 'KH',
  remoteIp: 'yawn perfectly',
  emailAddress: 'boot unless',
  timestamp: dayjs('2024-03-01T06:50'),
  state: 'repeatedly unrealistic',
  reasonCode: 'explode',
  message: 'phew eclipse opposite',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
