import dayjs from 'dayjs/esm';

import { IReconciliation, NewReconciliation } from './reconciliation.model';

export const sampleWithRequiredData: IReconciliation = {
  id: 11923,
  mandateId: 'if modulo forbid',
  paymentId: 'campus successfully',
  gateway: 'UNKNOWN',
  iban: 'EE380084305500506008',
  bic: 'ZBNLRULD',
  amount: 12011,
  currencyCode: 'NPR',
  softDescriptor: 'emit junior inauguration',
  firstName: 'Travis',
  lastName: 'Schaden',
  addressLine1: 'blanch where too',
  postalCode: 'warmly',
  city: 'Grand Junction',
  countryCode: 'SE',
  remoteIp: 'kooky',
  timestamp: dayjs('2024-02-29T15:44'),
  state: 'although',
  reasonCode: 'comply',
  message: 'preface savour',
};

export const sampleWithPartialData: IReconciliation = {
  id: 9477,
  mandateId: 'tube yet',
  paymentId: 'only geez',
  gateway: 'CCBILL',
  iban: 'TR530065882400501354401070',
  bic: 'QAUFAWI9KJN',
  amount: 12987,
  currencyCode: 'IDR',
  softDescriptor: 'yuck kneecap watchful',
  firstName: 'Pietro',
  lastName: 'Kuhic',
  addressLine1: 'boohoo',
  addressLine2: 'stealthily during determination',
  postalCode: 'incidentally pau',
  city: 'Port Jenafield',
  countryCode: 'VG',
  remoteIp: 'smarten',
  timestamp: dayjs('2024-02-29T17:11'),
  state: 'after properly',
  reasonCode: 'second-hand',
  message: 'leave pro',
};

export const sampleWithFullData: IReconciliation = {
  id: 9047,
  mandateId: 'reinforce bedrock',
  paymentId: 'knowingly fib',
  gateway: 'EMERCHANTPAY',
  iban: 'SA9048238929656FK62O2683',
  bic: 'HRKCKPQYJJT',
  amount: 21923,
  currencyCode: 'TOP',
  softDescriptor: 'demote validate',
  firstName: 'Emory',
  lastName: 'Gislason',
  addressLine1: 'crinoline ceiling sympathetically',
  addressLine2: 'apprehensive duh per',
  postalCode: 'when',
  city: 'Sawaynbury',
  countryCode: 'GF',
  remoteIp: 'feisty',
  timestamp: dayjs('2024-03-01T03:21'),
  state: 'lazily clear-cut jolly',
  reasonCode: 'after',
  message: 'couch',
  gatewayId: 'throughout slather',
  mode: 'furthermore opine but',
  fileName: 'positive wince',
};

export const sampleWithNewData: NewReconciliation = {
  mandateId: 'compliance rightfully gargle',
  paymentId: 'till',
  gateway: 'CCBILL',
  iban: 'DE79598807148005069098',
  bic: 'RKPTHKSU',
  amount: 3161,
  currencyCode: 'KHR',
  softDescriptor: 'surprisingly alongside mmm',
  firstName: 'Trudie',
  lastName: 'Bailey',
  addressLine1: 'until',
  postalCode: 'dislike physical',
  city: 'Eunicechester',
  countryCode: 'MK',
  remoteIp: 'near ack strand',
  timestamp: dayjs('2024-02-29T22:01'),
  state: 'yahoo bleakly',
  reasonCode: 'burglar',
  message: 'furthermore',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
