import dayjs from 'dayjs/esm';

import { IReconciliation, NewReconciliation } from './reconciliation.model';

export const sampleWithRequiredData: IReconciliation = {
  id: 25306,
  mandateId: 'blind repeatedly',
  paymentId: 'though woot familiarize',
  gateway: 'OPENPAYD',
  iban: 'AD32146006303775137172N3',
  bic: 'NTYJBH3I',
  amount: 12055,
  currencyCode: 'EGP',
  softDescriptor: 'though yuck sleepy',
  firstName: 'Krystal',
  lastName: 'Jast',
  streetName: 'Richie Green',
  houseNumber: 'highly nifty',
  postalCode: 'whereas how seal',
  city: 'West Mariane',
  countryCode: 'MX',
  remoteIp: 'but',
  emailAddress: 'tool true measly',
  timestamp: dayjs('2024-03-01T03:11'),
  state: 'resort wring bump',
  reasonCode: 'vacantly ack',
  message: 'corny pushy provided',
};

export const sampleWithPartialData: IReconciliation = {
  id: 12830,
  mandateId: 'clamp',
  paymentId: 'meadow',
  gateway: 'NOVALNET',
  iban: 'DE06001056520443008988',
  bic: 'FMYNWSX0',
  amount: 5534,
  currencyCode: 'QAR',
  softDescriptor: 'although row',
  firstName: 'Delbert',
  lastName: 'Upton',
  streetName: 'S Jefferson Street',
  houseNumber: 'supposing gloomy',
  postalCode: 'vibraphone gosh ',
  city: 'Schenectady',
  countryCode: 'JM',
  remoteIp: 'underneath usable mom',
  emailAddress: 'likewise upon',
  timestamp: dayjs('2024-02-29T14:13'),
  state: 'round',
  reasonCode: 'till',
  message: 'hydrocarbon briefly helpfully',
};

export const sampleWithFullData: IReconciliation = {
  id: 1242,
  mandateId: 'finally',
  paymentId: 'midwife minus per',
  gateway: 'EMERCHANTPAY',
  iban: 'FR5860889074523176937V1LE88',
  bic: 'BLCVHUCA3OY',
  amount: 30034,
  currencyCode: 'TZS',
  softDescriptor: 'ouch',
  firstName: 'Jerome',
  lastName: 'Zulauf',
  streetName: 'S Union Street',
  houseNumber: 'casket',
  postalCode: 'for gust excepti',
  city: 'Sioux Falls',
  countryCode: 'GG',
  remoteIp: 'fooey an needy',
  emailAddress: 'what',
  timestamp: dayjs('2024-03-01T08:59'),
  state: 'sturdy technician jiggle',
  reasonCode: 'reservation',
  message: 'perfumed wrongly save',
  gatewayId: 'import',
  mode: 'after',
  fileName: 'utilized medium',
};

export const sampleWithNewData: NewReconciliation = {
  mandateId: 'yesterday mean',
  paymentId: 'gently while clumsy',
  gateway: 'CCBILL',
  iban: 'HU48360487120457005010030002',
  bic: 'CFIIWS1W',
  amount: 1210,
  currencyCode: 'NOK',
  softDescriptor: 'inquisitively aircraft',
  firstName: 'Arden',
  lastName: 'Champlin',
  streetName: 'Cole Centers',
  houseNumber: 'pace',
  postalCode: 'hence verbally',
  city: 'West Bonnieberg',
  countryCode: 'MU',
  remoteIp: 'foodstuffs cafe admired',
  emailAddress: 'concerned',
  timestamp: dayjs('2024-03-01T06:11'),
  state: 'huff aboard amidst',
  reasonCode: 'derby',
  message: 'shinny',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
